name: four_detailer
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.32+62

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  croppy: ^1.3.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dropdown_search: ^6.0.1
  email_validator: ^3.0.0
  equatable: ^2.0.5
  file_picker: ^8.1.3
  flex_seed_scheme: ^3.4.1
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  flutter_native_splash: ^2.4.2
  flutter_svg: ^2.0.17
  geocoding: ^3.0.0
  get_it: ^8.0.1
  http: ^1.2.2
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  mime: ^1.0.2
  path: ^1.9.0
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  redacted: ^1.0.12
  responsive_framework: ^1.5.1
  supabase_flutter: ^2.8.2
  translations_cleaner: ^0.0.5
  wolt_modal_sheet: ^0.10.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  flutter_adaptive_scaffold: ^0.3.1
  material_design_icons_flutter: ^7.0.7296
  webview_flutter: ^4.10.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/launcher_icons/icon_black.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/launcher_icons/icon_black.png"
    background_color: "#000000"
    theme_color: "#000000"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/ccf/
